title: Conference Deadlines
description: Deadline countdowns for control/autonomy/aerospace conferences
author: Namhoon Cho (forked from Robert Moss and Abhishek Das)

domain: "nhcho91.github.io"
baseurl: "/control-deadlines"

github_username: nhcho91
github_repo: control-deadlines

markdown: kramdown
ga_id: 

include: ['_pages']
